import { STAGE_COLORS } from './stage-colors'
import type { PartnerTypeConfig, StageDefinition } from './types'

const FUNDER_STAGES: StageDefinition[] = [
  {
    id: 'prospect',
    label: 'Prospect',
    ...STAGE_COLORS.prospect,
    description: 'Identified as potential funder, research phase',
  },
  {
    id: 'in_discussion',
    label: 'In Discussion',
    ...STAGE_COLORS.in_discussion,
    description: 'Active conversations, proposal being prepared',
  },
  {
    id: 'agreed',
    label: 'Agreed',
    ...STAGE_COLORS.agreed,
    description: 'Funder said yes, terms being finalized',
  },
  {
    id: 'active',
    label: 'Active',
    ...STAGE_COLORS.active,
    description: 'Funds flowing, program running, reporting active',
  },
  {
    id: 'completed',
    label: 'Completed',
    ...STAGE_COLORS.completed,
    description: 'Grant period ended successfully',
    isTerminal: true,
  },
  {
    id: 'dropped',
    label: 'Dropped',
    ...STAGE_COLORS.dropped,
    description: 'Not proceeding',
    isTerminal: true,
    isDropped: true,
  },
]

export const FUNDER_CONFIG: PartnerTypeConfig = {
  entityType: 'funder',
  label: 'Funders',
  singularLabel: 'Funder',
  icon: 'DollarSign',
  baseRoute: '/partnerships/funders',
  apiRoute: '/api/funders',
  stages: FUNDER_STAGES,
  initialStage: 'prospect',
  terminalStages: ['completed', 'dropped'],
  dropReasons: [
    { value: 'not_aligned', label: 'Not aligned with our mission' },
    { value: 'budget_constraints', label: 'Their budget constraints' },
    { value: 'no_response', label: 'No response after attempts' },
    { value: 'program_ended', label: 'Program ended' },
    { value: 'relationship_issue', label: 'Relationship issue' },
    { value: 'other', label: 'Other' },
  ],
  listColumns: [
    { key: 'name', label: 'Funder', bold: true },
    { key: 'funder_type', label: 'Type', badge: true },
    { key: 'currentStage', label: 'Stage', badge: true, stageConfig: true },
    { key: 'active_commitment', label: 'Commitment', render: 'commitment_summary' },
    { key: 'assigned_co', label: 'CO', avatar: true },
    { key: 'updatedAt', label: 'Last Updated', relative: true },
  ],
  detailTabs: [
    { id: 'overview', label: 'Overview' },
    { id: 'contacts', label: 'POCs' },
    { id: 'interactions', label: 'Interactions' },
    { id: 'commitments', label: 'Commitments' },
    { id: 'deliverables', label: 'Deliverables' },
    { id: 'school-tags', label: 'Linked Schools' },
    { id: 'comments', label: 'Comments' },
  ],
  hasCommitments: true,
  hasDeliverables: true,
  hasSchoolTags: true,
  hasKanban: true,
  hasExport: true,
  canReallocateCo: true,
  canReactivate: true,
  createFormFields: [
    {
      name: 'name',
      label: 'Funder Name',
      type: 'text',
      required: true,
      placeholder: 'Organization or person name',
    },
    {
      name: 'funder_type',
      label: 'Funder Type',
      type: 'select',
      required: true,
      options: [
        { value: 'corporate', label: 'Corporate / Company' },
        { value: 'individual', label: 'Individual Donor' },
        { value: 'grant', label: 'Grant / Foundation' },
        { value: 'group', label: 'Group / Community' },
      ],
    },
    {
      name: 'state_id',
      label: 'State',
      type: 'select',
      required: true,
      options: [],
    },
    {
      name: 'city_id',
      label: 'City',
      type: 'select',
      required: true,
      options: [],
    },
    {
      name: 'website',
      label: 'Website',
      type: 'text',
      required: false,
      placeholder: 'https://...',
    },
    {
      name: 'co_id',
      label: 'Assign CO',
      type: 'select',
      required: true,
      options: [],
    },
  ],
}
