import { STAGE_COLORS } from './stage-colors'
import type { PartnerTypeConfig, StageDefinition } from './types'

const SOURCING_STAGES: StageDefinition[] = [
  {
    id: 'identified',
    label: 'Identified',
    ...STAGE_COLORS.identified,
    description: 'Organization identified as a potential sourcing partner',
  },
  {
    id: 'first_contact',
    label: 'First Contact',
    ...STAGE_COLORS.first_contact,
    description: 'Initial outreach made to the organization',
  },
  {
    id: 'in_discussion',
    label: 'In Discussion',
    ...STAGE_COLORS.in_discussion,
    description: 'Active discussions underway about partnership terms',
  },
  {
    id: 'onboarded',
    label: 'Onboarded',
    ...STAGE_COLORS.onboarded,
    description: 'Partner is onboarded and providing volunteers',
    isTerminal: true,
  },
  {
    id: 'paused',
    label: 'Paused',
    ...STAGE_COLORS.paused,
    description: 'Partnership temporarily paused',
  },
  {
    id: 'dropped',
    label: 'Dropped',
    ...STAGE_COLORS.dropped,
    description: 'Partnership ended — can be reactivated',
    isTerminal: true,
    isDropped: true,
  },
]

export const SOURCING_CONFIG: PartnerTypeConfig = {
  entityType: 'sourcing',
  label: 'Sourcing Partners',
  singularLabel: 'Sourcing Partner',
  icon: 'Users',
  baseRoute: '/partnerships/sourcing',
  apiRoute: '/api/partners/sourcing',
  stages: SOURCING_STAGES,
  initialStage: 'identified',
  terminalStages: ['onboarded', 'dropped'],
  dropReasons: [
    { value: 'no_response', label: 'No Response' },
    { value: 'program_mismatch', label: 'Program Mismatch' },
    { value: 'capacity_issues', label: 'Capacity Issues' },
    { value: 'relationship_ended', label: 'Relationship Ended' },
    { value: 'other', label: 'Other' },
  ],
  listColumns: [
    { key: 'partner_name', label: 'Organization', bold: true },
    { key: 'currentStage', label: 'Stage', badge: true, stageConfig: true },
    { key: 'assignedCo', label: 'Assigned CO', avatar: true },
    { key: 'org_type', label: 'Type' },
    { key: 'city', label: 'City' },
    { key: 'updatedAt', label: 'Last Updated', relative: true },
  ],
  detailTabs: [
    { id: 'overview', label: 'Overview' },
    { id: 'contacts', label: 'POCs' },
    { id: 'interactions', label: 'Interactions' },
    { id: 'commitments', label: 'Commitments' },
    { id: 'comments', label: 'Comments' },
  ],
  hasCommitments: true,
  hasSchoolTags: true,
  hasKanban: true,
  hasExport: true,
  canReallocateCo: true,
  canReactivate: true,
  createFormFields: [
    {
      name: 'partner_name',
      label: 'Organization Name',
      type: 'text',
      required: true,
      placeholder: 'e.g. ABC College',
    },
    {
      name: 'org_type',
      label: 'Organization Type',
      type: 'select',
      required: true,
      options: [
        { value: 'college', label: 'College / University' },
        { value: 'company', label: 'Company / Corporate' },
        { value: 'youth_club', label: 'Youth Club / NGO' },
        { value: 'government', label: 'Government Body' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      name: 'co_id',
      label: 'Assigned CO',
      type: 'select',
      required: true,
      placeholder: 'Select CO',
    },
    {
      name: 'state_id',
      label: 'State',
      type: 'select',
      required: true,
      placeholder: 'Select state',
    },
    {
      name: 'city_id',
      label: 'City',
      type: 'select',
      required: true,
      placeholder: 'Select city',
    },
    {
      name: 'address_line_1',
      label: 'Address',
      type: 'text',
      required: true,
      placeholder: 'Street / locality',
    },
    {
      name: 'pincode',
      label: 'Pincode',
      type: 'number',
      required: true,
      placeholder: '6-digit pincode',
    },
    {
      name: 'volunteer_capacity',
      label: 'Expected Volunteer Capacity',
      type: 'number',
      placeholder: 'Approx. volunteers per cycle',
      hint: 'Rough estimate of volunteers this org can send per year',
    },
    {
      name: 'lead_source',
      label: 'How was this partner identified?',
      type: 'select',
      required: true,
      options: [
        { value: 'referral', label: 'Referral' },
        { value: 'cold_outreach', label: 'Cold Outreach' },
        { value: 'event', label: 'Event / Conference' },
        { value: 'inbound', label: 'Inbound Inquiry' },
        { value: 'other', label: 'Other' },
      ],
    },
    {
      name: 'notes',
      label: 'Initial Notes',
      type: 'textarea',
      placeholder: 'Any initial observations or context…',
    },
  ],
}
